description:  ${spring.application.description}
title:  ${spring.application.name}
version:  ${spring.application.version}

info:
  app:
    id: ${spring.application.id}
    name: ${spring.application.name}
    version: ${spring.application.version}

server:
  port: 14000

spring:
  application:
    description: Lostboyz send email service
    id: lostboyz-email-user-service
    name: lostboyz-email-user-service
    version: 0.0.1-SNAPSHOT
  mail:
    default-encoding: UTF-8
    host: smtp.lostboyz.com # TODO: Change these per environment
    username: admin@lostboyz.com
    password: 86883e7f-77a2-4372-ad76-d9532084d9c0
    port: 25
    protocol: smtp
