description:  ${spring.application.description}
title:  ${spring.application.name}
version:  ${spring.application.version}

info:
  app:
    id: ${spring.application.id}
    name: ${spring.application.name}
    version: ${spring.application.version}

server:
  port: 14000

spring:
  application:
    description: Lostboyz send email service
    id: lostboyz-email-user-service
    name: lostboyz-email-user-service
    version: 0.0.1-SNAPSHOT
  mail:
    default-encoding: UTF-8
    host: ${SMTP_HOST}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: true
  output:
    ansi:
      enabled: detect

logging:
  file:
    name: logs/lostboyz-email-service.log
  level:
    root: ERROR